### ISSUE TITLE
Provide / Inject decorator 

### ISSUE THREAD

**Issue by nicolidin** [calebeaires/vue-decorator#2]
Hey

Thanks for this repo ! 
What about provide/inject decorator? 

The only way to use provide/inject actually is to do it through the`@Options` decorator (with vue-class-component), provide/inject is not accessible through `this.$` as for watch : `this.$watch`, I hope it is possible to implement it with a decorator. 

Thanks!

**Comment by calebeaires** [comment]
[vue-property-decorator](https://github.com/kaorun343/vue-property-decorator) has updated its project and now has provide/inject decorators. We update this project to offer all brand new sttuf.
